# Generated by Django 5.1.7 on 2025-03-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_userresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
