# Generated by Django 5.1.7 on 2025-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_alter_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
