# Generated by Django 5.1.7 on 2025-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_alter_questionnaire_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
