# Generated by Django 5.1.7 on 2025-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
