# Generated by Django 5.1.7 on 2025-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
