# Generated by Django 5.1.7 on 2025-04-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patientprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending')),
                ('health_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_agreements', to='users.healthprofessionalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_agreements', to='users.patientprofile')),
            ],
        ),
    ]
